import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={inter.className}>
        <div className='w-[100vw] h-[100vh] overflow-hidden flex border border-red-500'>
          <div className='w-[30%] border'>
            <Sidebar />
          </div>
          <div className='w-[70%]'>{children}</div>
        </div>
      </body>
    </html>
  );
}
